apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-pipeline-run-
spec:
  pipelineRef:
    name: ci-pipeline
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: next-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-06-serena-tim-e2e
    - name: image-repo
      value: quay.io/tim_walter_ibm/emea-06-next
  workspaces:
    - name: shared
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
    - name: production-repository
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
